name: Auto deploy web AnsTheLabel to Cpanel

on:
  push:
    branches: [ "dev" ]

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp           # pakai "ftps" jika server mewajibkan TLS
          port: 21
          local-dir: ./
          server-dir: public_html/ansthelabel.kawanlelah.com/
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            .env
            **/tests/**
